# Render Configuration
# This file is for Render.com deployment settings

# Build Command
build: pip install -r requirements-render.txt

# Start Command  
start: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120

# Environment
python_version: 3.11

# Health Check
health_check: /api/health

# Scaling
instances: 1
memory: 512MB

# Environment Variables needed:
# GEMINI_API_KEY=your_gemini_api_key
# OPENAI_API_KEY=your_openai_api_key
# MONGODB_URI=your_mongodb_connection_string (optional)
# FLASK_ENV=production