import React from 'react';
import { FiDownload, FiShare2, FiZoomIn } from 'react-icons/fi';
import LoadingSpinner from './LoadingSpinner';
import './ImageDisplay.css';

const ImageDisplay = ({ imageData, isGenerating, onImageSave, onImageExport }) => {
  const handleDownload = () => {
    if (imageData?.image_data) {
      const link = document.createElement('a');
      link.href = imageData.image_data;
      link.download = `echosketch-${Date.now()}.png`;
      link.click();
      if (onImageSave) onImageSave();
    }
  };

  const handleShare = () => {
    if (navigator.share && imageData?.image_data) {
      navigator.share({
        title: 'ECHOSKETCH Generated Image',
        text: `Generated visual from ECHOSKETCH`,
        url: imageData.image_data
      });
    } else if (imageData?.image_data) {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(imageData.image_data);
      if (onImageExport) onImageExport();
    }
  };

  return (
    <div className="image-display card">
      <div className="image-header">
        <h3>Generated Visual</h3>
        {imageData && (
          <div className="image-actions">
            <button className="action-btn" onClick={handleDownload} title="Download">
              <FiDownload size={16} />
            </button>
            <button className="action-btn" onClick={handleShare} title="Share">
              <FiShare2 size={16} />
            </button>
          </div>
        )}
      </div>

      <div className="image-content">
        {isGenerating ? (
          <div className="generating-state">
            <LoadingSpinner large message="Creating your visual..." />
          </div>
        ) : imageData ? (
          <div className="image-container">
            <img 
              src={imageData.image_data} 
              alt="Generated visual"
              className="generated-image"
            />
            <div className="image-info">
              <small>
                Generated by {imageData.service || 'AI'} | Size: {imageData.size || '512x512'}
              </small>
            </div>
          </div>
        ) : (
          <div className="image-placeholder">
            <div className="placeholder-icon">🎨</div>
            <p>Your generated image will appear here</p>
            <small>Start by recording your voice or typing a description</small>
          </div>
        )}
      </div>
    </div>
  );
};

export default ImageDisplay;